
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - ignore-for-release
      - "📦 packaging" 
      - "🔀 refactor"
      - "🤖 sys admin"
    authors:
      - octocat
  categories:
    - title: 🎉 New and improved
      labels:
        - "🌟 feature"
        - "✨ enhancement"
    - title: 🐛 Bug fixes
      labels:
        - "🐞 bug"
    - title: "📓 Docs, demos and testing" 
      labels:
        - "📓 docs & demos" 
        - "🔨 tests"