;=========== Uninstaller Data please do not edit this file ===========
RMDir /r "/Applications/PsychoPy 2025.1.0dev.app/Contents/_CodeSignature"
RMDir /r "/Applications/PsychoPy 2025.1.0dev.app/Contents/MacOS"
RMDir /r "/Applications/PsychoPy 2025.1.0dev.app/Contents/Resources"
RMDir /r "/Applications/PsychoPy 2025.1.0dev.app/Contents/Frameworks"
Delete "/Applications/PsychoPy 2025.1.0dev.app/Contents/CodeResources"
Delete "/Applications/PsychoPy 2025.1.0dev.app/Contents/Info.plist"
Delete "/Applications/PsychoPy 2025.1.0dev.app/Contents/PkgInfo"

