#This file was generated by generateHints.py.
#Following strings are used to localize hints in Preference Dialog of PsychoPy application.
#Rebuild this file if comments in *.spec files are modified.

#baseNoArch.spec,[general],line25
_translate("which system to use as a backend for drawing")

#baseNoArch.spec,[general],line27
_translate("the default units for windows and visual stimuli")

#baseNoArch.spec,[general],line29
_translate("full screen is best for accurate timing")

#baseNoArch.spec,[general],line31
_translate("enable subjects to use the mouse and GUIs during experiments")

#baseNoArch.spec,[general],line33
_translate("'version' is for internal usage, not for the user")

#baseNoArch.spec,[general],line35
_translate("Add paths here to your custom Python modules")

#baseNoArch.spec,[general],line37
_translate("choice of audio library")

#baseNoArch.spec,[general],line39
_translate("audio driver to use")

#baseNoArch.spec,[general],line41
_translate("path to flac (lossless audio compression) on this operating system")

#baseNoArch.spec,[general],line43
_translate("a list of parallel ports")

#baseNoArch.spec,[general],line46
_translate("display tips when starting PsychoPy")

#baseNoArch.spec,[app],line48
_translate("size of icons in the Coder and Builder toolbars (top of window)")

#baseNoArch.spec,[app],line50
_translate("what windows to display when PsychoPy starts")

#baseNoArch.spec,[app],line52
_translate("reset preferences to defaults on next restart of PsychoPy")

#baseNoArch.spec,[app],line54
_translate("save any unsaved preferences before closing the window")

#baseNoArch.spec,[app],line56
_translate("enable features for debugging PsychoPy itself, including unit-tests")

#baseNoArch.spec,[app],line58
_translate("language to use in menus etc; not all translations are available. Select a value, then restart the app.")

#baseNoArch.spec,[app],line60
_translate("a list of font names; the first one found on the system will be used")

#baseNoArch.spec,[app],line63
_translate("Font size (in pts) takes an integer between 6 and 24")

#baseNoArch.spec,[coder],line65
_translate("for coder shell window, which shell to use")

#baseNoArch.spec,[coder],line71
_translate("newline for python files: unix = \\n, dos = \\r\\n")

#baseNoArch.spec,[coder],line78
_translate("whether to automatically reload a previously open experiment")

#baseNoArch.spec,[coder],line80
_translate("if False will create scripts with an 'easier' but more cluttered namespace")

#baseNoArch.spec,[coder],line83
_translate("folder names for custom components; expects a comma-separated list")

#baseNoArch.spec,[builder],line85
_translate("a list of components to hide (eg, because you never use them)")

#baseNoArch.spec,[builder],line87
_translate("where the Builder demos are located on this computer (after unpacking)")

#baseNoArch.spec,[builder],line89
_translate("name of the folder where subject data should be saved (relative to the script)")

#baseNoArch.spec,[builder],line91
_translate("Panels arrangement: topFlow = Flow on top, Components on left")

#baseNoArch.spec,[builder],line93
_translate("Display text in a floating window that describes the experiment")

#baseNoArch.spec,[builder],line95
_translate("Upper limit on how many components can be in favorites")

#baseNoArch.spec,[builder],line97
_translate("the http proxy for usage stats and auto-updating; format is host: port")

#baseNoArch.spec,[builder],line99
_translate("override the above proxy settings with values found in the environment (if possible)")

#baseNoArch.spec,[builder],line101
_translate("allow PsychoPy to send anonymous usage stats; please allow if possible, its helps PsychoPy's development")

#baseNoArch.spec,[builder],line104
_translate("allow PsychoPy to check for new features and bug fixes")

#baseNoArch.spec,[connections],line106
_translate("max time to wait for a connection response")

#baseNoArch.spec,[connections],line108
_translate("open an existing file")

#baseNoArch.spec,[connections],line110
_translate("start a new experiment or script")

#baseNoArch.spec,[connections],line112
_translate("save a Builder or Coder file")

#baseNoArch.spec,[connections],line114
_translate("save a Builder or Coder file under a new name")

#baseNoArch.spec,[connections],line117
_translate("Coder: print the file")

#baseNoArch.spec,[keyBindings],line119
_translate("close the Builder or Coder window")

#baseNoArch.spec,[keyBindings],line121
_translate("end the application (PsychoPy)")

#baseNoArch.spec,[keyBindings],line123
_translate("open the preferences dialog")

#baseNoArch.spec,[keyBindings],line125
_translate("Coder: cut")

#baseNoArch.spec,[keyBindings],line127
_translate("Coder: copy")

#baseNoArch.spec,[keyBindings],line129
_translate("Coder: paste")

#baseNoArch.spec,[keyBindings],line131
_translate("Coder: duplicate")

#baseNoArch.spec,[keyBindings],line133
_translate("Coder: indent code by one level (4 spaces)")

#baseNoArch.spec,[keyBindings],line136
_translate("Coder: reduce indentation by one level (4 spaces)")

#baseNoArch.spec,[keyBindings],line138
_translate("Coder: indent to fit python syntax")

#baseNoArch.spec,[keyBindings],line140
_translate("Coder: find")

#baseNoArch.spec,[keyBindings],line142
_translate("Coder: find again")

#baseNoArch.spec,[keyBindings],line144
_translate("Coder: undo")

#baseNoArch.spec,[keyBindings],line146
_translate("Coder: redo")

#baseNoArch.spec,[keyBindings],line148
_translate("Coder: add a # to the start of the line(s)")

#baseNoArch.spec,[keyBindings],line150
_translate("Coder: remove # from start of line(s)")

#baseNoArch.spec,[keyBindings],line152
_translate("Coder: fold this block of code")

#baseNoArch.spec,[keyBindings],line154
_translate("Coder: check for basic syntax errors")

#baseNoArch.spec,[keyBindings],line156
_translate("convert a Builder .psyexp script into a python script and open it in the Coder")

#baseNoArch.spec,[keyBindings],line158
_translate("launch a script, Builder or Coder, or run unit-tests")

#baseNoArch.spec,[keyBindings],line160
_translate("attempt to interrupt and halt a running script")

#baseNoArch.spec,[keyBindings],line162
_translate("Coder: show / hide white-space dots")

#baseNoArch.spec,[keyBindings],line165
_translate("Coder: show / hide end of line characters")

#baseNoArch.spec,[keyBindings],line167
_translate("Builder: create a new routine")

#baseNoArch.spec,[keyBindings],line169
_translate("Builder: copy an existing routine")

#baseNoArch.spec,[keyBindings],line171
_translate("Builder: paste the copied routine")

#baseNoArch.spec,[keyBindings],line174
_translate("Coder: show / hide the output panel")

#baseNoArch.spec,[keyBindings],line176
_translate("switch to Builder window from Coder")

#baseNoArch.spec,[keyBindings],line180
_translate("switch to Coder window from Builder")

#baseNoArch.spec,[keyBindings],line182
_translate("increase display size in Flow")

#baseNoArch.spec,[keyBindings],line184
_translate("decrease display size in Flow")

#baseNoArch.spec,[keyBindings],line186
_translate("increase display size of Routines")

#baseNoArch.spec,[keyBindings],line188
_translate("decrease display size of Routines")

#baseNoArch.spec,[keyBindings],line190
_translate("show or hide the readme (info) for this experiment if possible")

