#This file was generated by generateHints.py.
#Following strings are used to localize hints in Preference Dialog of PsychoPy application.
#Rebuild this file if comments in *.spec files are modified.

#baseNoArch.spec,[general],line25
_("which system to use as a backend for drawing")

#baseNoArch.spec,[general],line27
_("the default units for windows and visual stimuli")

#baseNoArch.spec,[general],line29
_("full screen is best for accurate timing")

#baseNoArch.spec,[general],line31
_("enable subjects to use the mouse and GUIs during experiments")

#baseNoArch.spec,[general],line33
_("'version' is for internal usage, not for the user")

#baseNoArch.spec,[general],line35
_("Add paths here to your custom Python modules")

#baseNoArch.spec,[general],line37
_("choice of audio library")

#baseNoArch.spec,[general],line39
_("audio driver to use")

#baseNoArch.spec,[general],line41
_("path to flac (lossless audio compression) on this operating system")

#baseNoArch.spec,[general],line45
_("display tips when starting PsychoPy")

#baseNoArch.spec,[app],line47
_("size of icons in the Coder and Builder toolbars (top of window)")

#baseNoArch.spec,[app],line49
_("what windows to display when PsychoPy starts")

#baseNoArch.spec,[app],line51
_("reset preferences to defaults on next restart of PsychoPy")

#baseNoArch.spec,[app],line53
_("save any unsaved preferences before closing the window")

#baseNoArch.spec,[app],line55
_("enable features for debugging PsychoPy itself, including unit-tests")

#baseNoArch.spec,[app],line57
_("locale to use, e.g. en_US, en_US.UTF-8, ja_JP, etc; leave blank for default system locale")

#baseNoArch.spec,[app],line59
_("a list of font names; the first one found on the system will be used")

#baseNoArch.spec,[app],line62
_("Font size (in pts) takes an integer between 6 and 24")

#baseNoArch.spec,[coder],line64
_("for coder shell window, which shell to use")

#baseNoArch.spec,[coder],line70
_("newline for python files: unix = \\n, dos = \\r\\n")

#baseNoArch.spec,[coder],line77
_("whether to automatically reload a previously open experiment")

#baseNoArch.spec,[coder],line79
_("if False will create scripts with an 'easier' but more cluttered namespace")

#baseNoArch.spec,[coder],line82
_("folder names for custom components; expects a comma-separated list")

#baseNoArch.spec,[builder],line84
_("a list of components to hide (eg, because you never use them)")

#baseNoArch.spec,[builder],line86
_("where the Builder demos are located on this computer (after unpacking)")

#baseNoArch.spec,[builder],line88
_("name of the folder where subject data should be saved (relative to the script)")

#baseNoArch.spec,[builder],line90
_("Panels arrangement: topFlow = Flow on top, Components on left")

#baseNoArch.spec,[builder],line92
_("Display text in a floating window that describes the experiment")

#baseNoArch.spec,[builder],line94
_("Upper limit on how many components can be in favorites")

#baseNoArch.spec,[builder],line96
_("the http proxy for usage stats and auto-updating; format is host: port")

#baseNoArch.spec,[builder],line98
_("override the above proxy settings with values found in the environment (if possible)")

#baseNoArch.spec,[builder],line100
_("allow PsychoPy to send anonymous usage stats; please allow if possible, its helps PsychoPy's development")

#baseNoArch.spec,[builder],line103
_("allow PsychoPy to check for new features and bug fixes")

#baseNoArch.spec,[connections],line105
_("max time to wait for a connection response")

#Windows.spec,[app],line60
_("locale to use, e.g. ENG, DEU, DAN, JPN, etc; leave blank for default system locale")

