Document: psychopy
Title: Debian psychopy Manual
Author: <insert document author here>
Abstract: This manual describes what psychopy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/psychopy/psychopy.sgml.gz

Format: postscript
Files: /usr/share/doc/psychopy/psychopy.ps.gz

Format: text
Files: /usr/share/doc/psychopy/psychopy.text.gz

Format: HTML
Index: /usr/share/doc/psychopy/html/index.html
Files: /usr/share/doc/psychopy/html/*.html

  
