#!/usr/bin/env python
# -*- coding: utf-8 -*-

# This file was generated by generateAlertmsg.py.
# Following strings are used to localize alerts.
# Rebuild this file if alert messages in *.yaml files are modified.

from __future__ import absolute_import, print_function
from psychopy.localization import _translate

# Alert 2115
_translate(
    "Your stimulus size exceeds the {dimension} dimension of your window.")

# Alert 2120
_translate(
    "Your stimulus size is smaller than 1 pixel ({dimension} dimension).")

# Alert 2155
_translate(
    "Your stimulus position exceeds the {dimension} dimension of your window.")

# Alert 3110
_translate(
    "Your stimulus {type} time of {time} is less than a screen refresh for a {Hz}Hz monitor.")

# Alert 3115
_translate(
    "Your stimulus {type} time of {time} seconds cannot be accurately presented for {time} on a {Hz}Hz monitor.")

# Alert 4105
_translate(
    "Your stimulus start {type} exceeds the stop {type}. Consider using a {type} duration.")

# Alert 4115
_translate(
    "Your stimulus {type} type {frameType} must be expressed as a whole number.")

# Alert 4205
_translate(
    "Python Syntax Error in '{codeTab}' tab. See '{code}' on line number {lineNumber} of the '{codeTab}' tab.")

# Alert 4210
_translate(
    "JavaScript Syntax Error in '{codeTab}' tab. See '{lineNumber}' in the '{codeTab}' tab.")

# Alert 4305
_translate(
    "Your component is currently disabled and will not be written to your experiment script.")

# Alert 4310
_translate("Cannot calculate parameter.")

# Alert 4315
_translate(
    "Builder cannot interpret value \"{param.val}\" of {param.label} for {component.type} component \"{component.params[name].val}\" as a dollar sign has been used incorrectly.")

# Alert 4320
_translate(
    "Font `{param.val}` not found locally, will check Google Fonts on next run.")

# Alert 6105
_translate(
    "The file you are attempting to run does not seem to exist, the full path supplied to Runner was {path}")
