NOT_STARTED = 0
PLAYING = 1
STARTED = PLAYING
PAUSED = 2
STOPPED = -1
FINISHED = STOPPED

# for button box:
PRESSED = 1
RELEASED = -1

FOREVER = 1000000000 # seconds; while t < FOREVER ... # in scripts generated by Builder

# USERAGENT is for consistent http-related self-identification across an app. It
# shows up in server logs on the receiving end. Currently the value (and its use
# from psychopy) is arbitrary and optional. But it will need to be used and be
# fixed if a) google starts charging for using their speech-recognition API and
# b) uses the same model as for translation (both of which seem relatively likely
# in the long run). Having it standardized and fixed will also help people who
# develop their own http-log analysis tools for use with contrib.http.upload()
PSYCHOPY_USERAGENT = "PsychoPy: open-source Psychology & Neuroscience tools; www.psychopy.org"
