NOT_STARTED = 0
PLAYING = 1
STARTED = PLAYING
PAUSED = 2
STOPPED = -1
FINISHED = STOPPED

FOREVER = 1000000000 # seconds; while t < FOREVER ... # in scripts generated by Builder

# for consistent http-related self-identification across the app:
PSYCHOPY_USERAGENT = "PsychoPy: open-source Psychology & Neuroscience tools; www.psychopy.org"
