#!/usr/bin/env python2
# -*- coding: utf-8 -*-
from __future__ import division, print_function, absolute_import
"""Testing the iohub.launchHubServer function illustrating different ways
it can be used.

No PsychoPy Window is created for this demo; results are printed to stdout.
"""

import time
from pprint import pprint

from psychopy.iohub.client import launchHubServer


def launchWithNoKwargs():
    """
    launchWithNoKwargs illustrates using the launchHubServer function with no
    parameters at all. Considerations:
        * Default Keyboard, Mouse, Monitor, and Experiment devices are created.
        * ioHub DataStore is not enabled.
    """
    io = launchHubServer()
    keyboard = io.devices.keyboard

    keyboard.clearEvents()
    
    print()
    print(' ** PRESS A KEY TO CONTINUE.....')

    keyboard.waitForPresses()

    print('A Keyboard Event was Detected; exiting Test.')

    io.quit()


def launchUsingPsychoPyMonitorConfig():
    """
    launchUsingPsychoPyMonitorConfig illustrates providing a PsychoPy monitor
    configuration file name to the launchHubServer function.
    Considerations:
        * Default Keyboard, Mouse, Monitor, and Experiment devices are created.
        * If the psychopy_monitor_name is valid, the ioHub Display size and
          viewing distance are updated using the psychopy monitor config.
        * ioHub DataStore is not enabled.
    """

    io = launchHubServer(psychopy_monitor_name='testMonitor')

    # Get the default display device created.
    display = io.devices.display

    print('Display Psychopy Monitor Name: ', display.getPsychopyMonitorName())
    print('Display Default Eye Distance: ', display.getDefaultEyeDistance())
    print('Display Physical Dimensions: ', display.getPhysicalDimensions())

    # That's it, shut down the ioHub Proicess and exit. ;)
    io.quit()


def launchEnabledDataStore():
    """
    launchEnabledDataStore illustrates that by adding an experiment_code
    kwarg to launchHubServer(....), an ioHub HDF5 file is created by the
    ioHub Server which saves all the device events.

    Experiment and session metadata is printed at the end of the demo.
    Considerations:
        * Default Keyboard, Mouse, Monitor, and Experiment devices are created.
        * ioHub DataStore is enabled: ioHub Server saves events to a HDF5 file.
        * session_code is autogenerated based on the current date/time.
        * session_code is used to name the saved HDF5 file.
    """
    exp_code = 'gap_endo_que'
    io = launchHubServer(experiment_code=exp_code)

    print('Experiment Metadata: ')
    pprint(io.getExperimentMetaData())
    print('\nSession Metadata: ')
    pprint(io.getSessionMetaData())

    io.quit()


def launchAutoSessionCode():
    """
    launchAutoSessionCode is the same as launchEnabledDataStore
    above, but session_code is provided by the script instead of being
    auto-generated. The ioHub DataStore will be enabled, using the
    experiment and session_code provided each time it is run. Experiment
    and session metadata is printed at the end of the demo.

    Considerations:
        * Default Keyboard, Mouse, Monitor, and Experiment devices are created.
        * ioHub DataStore is enabled: ioHub Server saves events to a HDF5 file.
        * session_code is used to name the saved HDF5 file.
    """
    exp_code = 'gap_endo_que'
    sess_code = 'S_{0}'.format(long(time.mktime(time.localtime())))
    print('Current Session Code will be: ', sess_code)

    io = launchHubServer(experiment_code=exp_code,
                         session_code=sess_code)

    print('Experiment Metadata: ')
    pprint(io.getExperimentMetaData())
    print('\nSession Metadata: ')
    pprint(io.getSessionMetaData())

    io.quit()


if __name__ == '__main__':
    demo_list = [launchWithNoKwargs, launchUsingPsychoPyMonitorConfig,
                 launchEnabledDataStore, launchAutoSessionCode]
    for demo in demo_list:
        print('\n------------------------------------\n')
        print('Running %s Example:' % (demo.__name__))
        demo()

