name: pytest

on:
  workflow_dispatch:  # manual
  pull_request:
   branches: [ release, dev ]

permissions:
  contents: read

jobs:

  testsuite:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-22.04]
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3

    - name: Install UV
      uses: astral-sh/setup-uv@v7
    
    - name: setup_python
      id: python
      run: |
        # use uv to install a base Python executable
        if [ "${{ runner.os }}" == "macOS" ]
        then
          # on mac this needs to be the intel build specifically
          curl -L https://github.com/astral-sh/python-build-standalone/releases/download/20251209/cpython-3.10.19+20251209-x86_64-apple-darwin-install_only.tar.gz --output ~/pythonIntel.tar.gz
          mkdir ~/pythonIntel
          tar -xzvf ~/pythonIntel.tar.gz -C ~/pythonIntel
          export PYTHON_EXECUTABLE=$(uv python find ~/pythonIntel/python)
        else
          uv python install ${{ matrix.python-version }}
          export PYTHON_EXECUTABLE=$(uv python find ${{ matrix.python-version }})
        fi
        # create a venv so any subsequent python calls use this executable
        uv venv --clear --python $PYTHON_EXECUTABLE
        # return executable
        echo "executable=$PYTHON_EXECUTABLE" >> "$GITHUB_OUTPUT"

    - name: get_month
      if: runner.os=='Linux'
      id: month
      run: echo "month=$(date +'%Y-%m')" >> "$GITHUB_OUTPUT"
  
    - name: cache wxPython for linux
      if: runner.os=='Linux'
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ matrix.os }}-py${{ matrix.python-version }}-${{ steps.month.outputs.month }}
        
    - name: Install Linux system dependencies
      if: runner.os=='Linux'
      run: |
        # mostly for wxPython:
        sudo apt-get update
        sudo apt-get install -y -qq python3-dev libgtk-3-dev
        sudo apt-get install -y -qq libgstreamer1.0-0 gstreamer1.0-plugins-base
        sudo apt-get install -y -qq libwebkit2gtk-4.0-dev
        sudo apt-get install -y -qq libpng-dev libjpeg-dev libtiff-dev libnotify-dev libsm-dev
        sudo apt-get install -y -qq libsdl2-dev libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-2.0-0
        sudo apt-get install -y -qq libportaudio2
        sudo apt-get install -y -qq python3-typing-extensions
        # virtual frame buffer
        sudo apt install llvm-13-dev  # for xvfb
        sudo apt install xvfb xauth libgl1-mesa-dri

        # set up fake sound device?
        # sudo apt-get install -y -qq libasound2-dev alsa-utils alsa-oss
        # sudo apt-get install -y linux-modules-extra-$(uname -r)  # needed for modprobe snd-dummy
        # sudo sh .github/workflows/prep_dummy_soundcard.sh  # couldn't find that file

        # for PyQt:
        sudo apt-get install -y -qq libdbus-1-3
        sudo apt-get install -y -qq '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
        export LIBGL_ALWAYS_INDIRECT=0
        export QT_DEBUG_PLUGINS=1 # let us know about missing dependencies?

        # for wxPython
        uv pip install https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxpython-4.2.4-cp310-cp310-linux_x86_64.whl

    - name: Pre-Install
      run: |
        uv pip install wheel packaging six attrdict3 moviepy git+https://gitlab.com/peircej/metapensiero.pj pdm
        if [ "${{ runner.os }}" == "Windows" ]
        then
          uv pip install pyWinhook --default-index https://www.lfd.uci.edu/~gohlke/pythonlibs
        fi
        if [ "${{ runner.os }}" == "macOS" ]
        then
          # for pocketsphinx we need this adapted package:
          brew install swig vlc portaudio portmidi liblo sdl2
        fi
    
    - name: Install
      run: |
        uv pip install . .[tests]
    
    - name: Set nice level (linux)
      if: runner.os=='Linux'
      run: |
        # sudo setcap cap_sys_nice=eip ${{ env.pythonLocation }}/python
        sudo setcap cap_sys_nice+ep "${{ steps.python.outputs.executable }}"
        getcap "${{ steps.python.outputs.executable }}"  # did it work?

    - name: Test gui toolkits
      if: runner.os=='Linux'
      run: |
        # quick test of the gui toolkits (without pytest swallowing errors)
        xvfb-run -a --server-args="-screen 0 1024x768x24" uv run psychopy/tests/test_gui/test_DlgFromDictQt.py
        xvfb-run -a --server-args="-screen 0 1024x768x24" uv run psychopy/tests/test_gui/test_DlgFromDictWx.py

    - name: Test with pytest
      run: |
        if [ "${{ runner.os }}" == "Linux" ]
        then
          xvfb-run -a --server-args="-screen 0 1024x768x24" uv run pytest -m "not needs_sound and not needs_wx and not needs_qt and not needs_pygame and not emulator" --cov=psychopy -v psychopy
        else
          uv run pytest --ignore="psychopy/tests/test_app" --ignore="psychopy/tests/test_preferences" --ignore="psychopy/tests/test_experiment/needs_wx" -m "not needs_sound and not needs_wx and not emulator"  --cov=psychopy -v psychopy
        fi

    - name: upload failed app data
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: prefs_files_${{ matrix.os }}_${{ matrix.python-version }}
        path: |
          ~/.psychopy3
          !~/.psychopy3/versions
          !~/.psychopy3/fonts

    - name: upload failed screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: failed_test_data_${{ github.run_id }}_${{ matrix.python-version }}_${{ matrix.os }}
        path: |
          psychopy/tests/fails
          !**/*.mp4
          !psychopy/tests/**/*.data
          !**/*.wav

    - name: Upload coverage to Codecov
      if: always()
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: false

#    - name: test docs to pdf
#      run: |
#          pip install sphinx sphinxcontrib-napoleon
#          brew install basictex
#          # update path after brew install
#          eval "$(/usr/libexec/path_helper)"
#          # go to the folder and make
#          cd docs
#          make latexpdf
#          cd ..


#    - name: Check bdist/sdist
#      # checks whether different forms of build work (e.g. missing files in sdist)
#      run: |
#        python setup.py build
#        # Build & install sdist
#        python setup.py sdist --formats=gztar
#        pip install --no-deps dist/PsychoPy-*.tar.gz
#        pip uninstall --yes psychopy
#        # Build & install wheel
#        python setup.py bdist_wheel
#        pip install --no-deps dist/PsychoPy-*.whl
#        # uninstall the build (but not the dependencies)
#        pip uninstall --yes psychopy

#    - name: test docs to pdf
#      if: runner.os=='Linux'
#      run: |
#        sudo apt-get install -y python3-sphinx
#        which sphinx-build
#        which python
#        python -c "import psychopy; psychopy"
#        #        sudo apt-get install -y latexmk xindy texlive-latex-recommended texlive-xetex texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
#        #        cd docs
#        #        make latexpdf
#        #        cd ..
